### ISSUE TITLE
Save Yang Diagram

### ISSUE THREAD

**Issue by FaizanFrolic** [TypeFox/yang-vscode#72]
Can we have the option to save the yang diagram with good resolution? When the yang file is big we can not take a screenshot that fits in page

**Comment by dhuebner** [comment]
@FaizanFrolic 
Is it not exported as SVG? For an SVG it is no problem to scale afterwards. 
Also I think it's a Sprotty feature, need to investigate first.

**Comment by FaizanFrolic** [comment]
@dhuebner mouse right-click does not work on the image. tried the "file-> save as" option but doesn't work. do we have any command to save the file as SVG? or does it saved by default to some default location on the system?

**Comment by dhuebner** [comment]
@FaizanFrolic 
> do we have any command to save the file as SVG? 

There is a [Sprotty feature](https://github.com/eclipse-sprotty/sprotty/blob/master/packages/sprotty/src/features/export/export.ts#L35) for SVG export. On Mac it's `CMD+Shift+E`, thought didn't try it with Yang diagrams.

**Comment by dhuebner** [comment]
@FaizanFrolic 
It works for me with Yangster using `ALT-E`, see [here](https://github.com/TypeFox/yang-vscode/blob/028658b0dbbc989806d76e0340ad79a22847ec32/package.json#L119)

**Comment by FaizanFrolic** [comment]
@dhuebner 
Thank You :)
