### ISSUE TITLE
yang.settings file should be associated as JSON by default

### ISSUE THREAD

**Issue by esmasth** [TypeFox/yang-vscode#81]
Currently manual association has to be added globally or per project/workspace .vscode/settings.json. This could be avoided by the plugin doing it instead of the developer.

**Comment by esmasth** [comment]
Since the YANG LSP yang.settings supports // comments, it would be good to classify it as "JSON with Comments" to allow for documentation of the settings

**Comment by dhuebner** [comment]
Merged
