### ISSUE TITLE
yang.settings associated with its JSON Schema

### ISSUE THREAD

**Issue by esmasth** [TypeFox/yang-vscode#82]
Typefox/yang-lsp#233 discusses the dependency of this enhancement. A JSON Schema which is provided by YANG LSP from origin could be associated by the Yangster plugin here for ease of developer experience. Otherwise the developer would have to associate json schema manually.

Reference https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation

**Comment by dhuebner** [comment]
Merged
